---
- hosts: local
  become: True
  roles:
  - role: common
  - role: chrome
  - role: games
  - role: node
  - role: docker
  - role: php7
  - role: virtualbox
  - role: vscode

- hosts: local
  become: False
  roles:
  - role: xfce4
