---
- hosts: local
  become: yes
  roles:
  - role: common
  - role: chrome
  - role: games
  - role: node
  - role: docker
  - role: php7
  - role: mysql
  - role: virtualbox
  - role: vscode

- hosts: local
  become: yes
  become_user: "{{ ansible_user }}"
  roles:
  - role: xfce4
  - role: dotenvs
