---
- hosts: local
  become: yes
  roles:
  - { role: common, tags: [common] }
  - { role: chrome, tags: [chrome] }
  - { role: games, tags: [games] }
  - { role: node, tags: [node] }
  - { role: docker, tags: [docker] }
  - { role: php7, tags: [php7] }
  - { role: vscode, tags: [vscode] }

- hosts: local
  become: yes
  become_user: "{{ ansible_user }}"
  roles:
  - { role: xfce4, tags: [xfce4] }
  - { role: dotenvs, tags: [dotenvs] }
