---
- hosts: local
  become: yes
  vars_files:
    - ./app_versions.yml
  roles:
  - { role: common, tags: [common] }
  - { role: common-extra, tags: [common-extra] }
  - { role: chrome, tags: [chrome] }
  - { role: games, tags: [games] }
  - { role: node, tags: [node] }
  - { role: golang, tags: [golang] }
  - { role: docker, tags: [docker] }
  - { role: vscode, tags: [vscode] }
  - { role: devops-stuff, tags: [devops-stuff] }

- hosts: local
  become: yes
  become_user: "{{ ansible_user }}"
  roles:
  - { role: xfce4, tags: [xfce4] }
  - { role: dotenvs, tags: [dotenvs] }
