- block:
  # https://code.visualstudio.com/docs/setup/linux
  - name: Add VSCode key
    ansible.builtin.get_url:
      url: https://packages.microsoft.com/keys/microsoft.asc
      dest: /etc/apt/trusted.gpg.d/microsoft.asc
      owner: root
      group: root
      mode: '0644'

  - name: Add VSCode repository
    apt_repository:
      repo: deb [arch=amd64] https://packages.microsoft.com/repos/code stable main
      state: present
      filename: vscode

  - name: Update repositories
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Install VSCode
    apt:
      name: code
      state: present
