# TODO
# xfce4 panels setup + plugins
# lightdm login configuration to list users greeter-hide-users=false
---
- block:
  - name: Install themes and icons for desktop configuration
    apt:
      name: "{{ item }}"
      state: present
    loop:
    - fonts-hack-ttf
    - fonts-lyx
    - fonts-noto
    - fonts-noto-cjk
    - fonts-noto-hinted
    - fonts-noto-unhinted
    - numix-gtk-theme
    - numix-icon-theme

  - name: Copy xfce4 panel configuration files
    copy:
      src: files/xfce4.zip
      dest: "/home/{{ ansible_user }}/.config/xfce4.zip"
