- block:
  - name: Install themes and icons for desktop configuration
    apt:
      name: "{{ item }}"
      state: present
    loop:
    - fonts-hack-ttf
    - ttf-bitstream-vera
    - fonts-lyx
    - fonts-noto
    - fonts-noto-cjk
    - fonts-noto-hinted
    - fonts-noto-unhinted
    - numix-gtk-theme
    - numix-icon-theme
    become: yes
    become_user: root

  - name: Create wallpapers directory
    file:
      path: "{{ item }}"
      state: directory
      owner: "{{ ansible_user }}"
    with_items:
    - /home/{{ ansible_user }}/tmp
    - /home/{{ ansible_user }}/tmp/wallpapers

  - name: Copy wallpaper file
    copy:
      src: files/city.jpg
      dest: "/home/{{ ansible_user }}/tmp/wallpapers/city.jpg"

  - name: Make sure .config exists
    file:
      state: directory
      path: "/home/{{ ansible_user }}/.config"
      owner: "{{ ansible_user }}"

  - name: Copy xfce4 panel configuration files
    copy:
      src: files/xfce4.zip
      dest: "/home/{{ ansible_user }}/.config/xfce4.zip"

  - name: Display users on lightdm
    lineinfile:
      regex: '^#greeter-hide-users=false$'
      line: 'greeter-hide-users=false'
      path: /etc/lightdm/lightdm.conf
    become: yes
    become_user: root
