---
- name: Download Bat
  get_url:
    url: "https://github.com/sharkdp/bat/releases/download/v{{ bat_version }}/bat-v{{ bat_version }}-x86_64-unknown-linux-gnu.tar.gz"
    dest: /opt/bat.tar.gz
    mode: 0755

- name: Create bat directory
  file:
    path: /opt/bat
    state: directory
    mode: 0755

- name: Unarchive Bat
  ansible.builtin.unarchive:
    src: /opt/bat.tar.gz
    dest: /opt/bat
    creates: /opt/bat/bat-v{{ bat_version }}-x86_64-unknown-linux-gnu
    remote_src: no

- name: Copy Bat binary to global path
  copy:
    src: /opt/bat/bat-v{{ bat_version }}-x86_64-unknown-linux-gnu/bat
    dest: /usr/local/bin/bat
    mode: 0755

- name: Delete bat directory
  file:
    path: /opt/bat
    state: absent
