- block:
  - name: Add MySQL repository key
    apt_key:
      data: "{{ lookup('file', 'files/mysql.gpg') }}"
      state: present

  - name: Add MySQL repositories
    apt_repository:
      repo: "{{ item }}"
      state: present
      filename: mysql
    loop:
    - deb http://repo.mysql.com/apt/debian/ buster mysql-5.7
    - deb http://repo.mysql.com/apt/debian/ buster mysql-tools

  - name: Update repositories
    apt:
      update_cache: yes
      force: yes

  - name: Install MySQL 5.7 and other required packages
    apt:
      name: "{{ item }}"
      state: present
    loop:
    - mysql-server
    - python-mysqldb

  - name: Start the MySQL service
    service:
      name: mysql
      state: started
      enabled: true

  # Remember this is for local development only
  # and not for a production MySQL server
  - name: Configure MySQL root user
    mysql_user:
      name: root
      host: "{{ item }}"
      password: "12345"
      login_user: root
      login_password: "12345"
      check_implicit_admin: yes
      priv: "*.*:ALL,GRANT"
      login_unix_socket: /var/run/mysqld/mysqld.sock
    with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost
