- block:
  - name: Add tmux configuration file
    template:
      src: templates/tmux.conf
      dest: "/home/{{ ansible_user }}/.tmux.conf"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"

  - name: Basic configuration for vim
    template:
      src: templates/vimrc
      dest: "/home/{{ ansible_user }}/.vimrc"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"

  - name: Add tmux rates plugin
    template:
      src: templates/tmux_rates.sh
      dest: "/home/{{ ansible_user }}/.local/bin/tmux_rates.sh"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: 0755

  - name: Add tmux get_rates.sh
    template:
      src: templates/tmux_get_rates.sh
      dest: "/home/{{ ansible_user }}/.local/bin/tmux_get_rates.sh"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: 0755

  - name: Add tmux get rates crontab
    cron:
      name: get rates for tmux
      user: "{{ ansible_user }}"
      job: "/home/{{ ansible_user }}/.local/bin/tmux_get_rates.sh"
      minute: "*/15"

  - name: Add command prompt customization
    copy:
      src: templates/custom_prompt.sh
      dest: "/home/{{ ansible_user }}/.bash_aliases"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: 0644

  - name: Create MOC configuration directories
    file:
      state: directory
      path: "/home/{{ ansible_user }}/{{ item }}"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
    loop:
    - .moc
    - .moc/themes

  - name: Add MOC player configuration file
    template:
      src: templates/moc_conf
      dest: "/home/{{ ansible_user }}/.moc/config"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: "0600" # newer versions require this files to have group set to zero

  - name: Add MOC player configuration file
    template:
      src: templates/moc_black_theme
      dest: "/home/{{ ansible_user }}/.moc/themes/black_theme"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
