- block:
  # From: https://www.google.com/linuxrepositories/
  - name:
    ansible.builtin.get_url:
      url: https://dl.google.com/linux/linux_signing_key.pub
      dest: /etc/apt/trusted.gpg.d/google.asc
      owner: root
      group: root
      mode: '0644'

  - name: Add Chrome apt repository
    apt_repository:
      repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
      filename: google-chrome
      state: present

  - name: Update repositories
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Install Google Chrome
    apt:
      name: google-chrome-stable
      state: present
