- block:
  - name: Add Virtualbox key
    apt_key:
      url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
      state: present

  # Change to buster when Virtualbox supports it in its repos
  # https://www.virtualbox.org/ticket/17878
  - name: Add Virtualbox repository
    apt_repository:
      repo: deb http://download.virtualbox.org/virtualbox/debian bionic contrib
      state: present
      filename: virtualbox

  - name: Update repositories
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Install virtualbox
    apt:
      name: virtualbox-6.0
      state: present
