- block:
  - name: Check variables
    ansible.builtin.assert:
      that:
      - node_version != ''
      - debian_version != ''
      quiet: true

  - name: Add NodeJS apt-key
    apt_key:
      keyserver: keyserver.ubuntu.com
      # From: https://keyserver.ubuntu.com/pks/lookup?search=1655A0AB68576280&fingerprint=on&op=index
      id: 9fd3b784bc1c6fc31a8a0a1c1655a0ab68576280
      state: present

  - name: Add NodeJS repository
    apt_repository:
      repo: "deb https://deb.nodesource.com/{{ node_version }} nodistro main"
      filename: nodejs

  - name: Update repositories
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Install NodeJS
    apt:
      name: nodejs
      state: present
