- block:
  - name: Check variables
    ansible.builtin.assert:
      that:
      - node_version != ''
      - debian_version != ''
      quiet: true

  - name: Add NodeJS apt-key
    apt_key:
      url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
      state: present

  - name: Add NodeJS repository
    apt_repository:
      repo: "deb https://deb.nodesource.com/{{ node_version }} {{ debian_version }} main"
      filename: nodejs

  - name: Update repositories
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Install NodeJS
    apt:
      name: nodejs
      state: present
