- block:
  - name: Check variables
    ansible.builtin.assert:
      that:
      - node_version != ''
      - debian_version != ''
      quiet: true

  - name: Add NodeJS key
    shell: |
      curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --yes --dearmor -o /usr/share/keyrings/nodesource.gpg

  - name: Add NodeJS repository
    apt_repository:
      repo: "deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/{{ node_version }} nodistro main"
      filename: nodejs

  - name: Update repositories
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Install NodeJS
    apt:
      name: nodejs
      state: present
