- block:
  - name: Add Sury php7 apt key
    apt_key:
      url: https://packages.sury.org/php/apt.gpg
      state: present

  - name: Add Sury repository
    apt_repository:
      repo: "deb https://packages.sury.org/php/ stretch main"
      filename: php7-sury

  - name: Add MySQL repository key
    apt_key:
      data: "{{ lookup('file', 'files/mysql.gpg') }}"
      state: present

  - name: Add MySQL repositories
    apt_repository:
      repo: "{{ item }}"
      state: present
      filename: mysql
    loop:
    - deb http://repo.mysql.com/apt/debian/ stretch mysql-5.7
    - deb http://repo.mysql.com/apt/debian/ stretch mysql-tools

  - name: Update repositories
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Install php7
    apt:
      name: "{{ item }}"
      state: present
    loop:
    - php7.2-bcmath
    - php7.2-cli
    - php7.2-common
    - php7.2-curl
    - php7.2-fpm
    - php7.2-json
    - php7.2-mbstring
    - php7.2-mysql
    - php7.2-opcache
    - php7.2-readline
    - php7.2-sqlite3
    - php7.2-xml
    - php7.2-zip

  - name: Install MySQL 5.7
    apt:
      name: mysql-server
      state: present
