- block:
  - name: Add Sury php7 apt key
    apt_key:
      url: https://packages.sury.org/php/apt.gpg
      state: present

  - name: Add Sury repository
    apt_repository:
      repo: "deb https://packages.sury.org/php/ buster main"
      filename: php7-sury

  - name: Update repositories
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Install php7
    apt:
      name: "{{ item }}"
      state: present
    loop:
    - php7.2-bcmath
    - php7.2-cli
    - php7.2-common
    - php7.2-curl
    - php7.2-fpm
    - php7.2-json
    - php7.2-mbstring
    - php7.2-mysql
    - php7.2-opcache
    - php7.2-readline
    - php7.2-sqlite3
    - php7.2-xml
    - php7.2-zip
