- block:
  - name: Download kubectl
    get_url:
      url: https://dl.k8s.io/release/v{{ kubectl_version }}/bin/linux/amd64/kubectl
      dest: /usr/local/bin/kubectl
      mode: 0755

  - name: Add tab kubectl autocompletion
    copy:
      dest: /home/{{ ansible_user }}/.my-bash-confs/kubectl.rc
      content: |
        # Enable kubectl autocompletion
        source <(kubectl completion bash)
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"

  - name: Download terraform
    get_url:
      url: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip
      dest: /opt/terraform.zip

  - name: Uncompress terraform
    ansible.builtin.unarchive:
      src: /opt/terraform.zip
      dest: /usr/local/bin/
      remote_src: no

# https://github.com/gohugoio/hugo/releases/download/v{{ hugo_version }}/hugo_{{ hugo_version }}_Linux-64bit.tar.gz
#
