- block:
  - name: Add Docker CE apt key
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present

  - name: Add Docker CE repository
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ debian_version }} stable"
      filename: docker-ce

  - name: Update repositories
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Install Docker CE
    apt:
      name: "{{ item }}"
      state: present
    loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

  - name: Add ansible user to docker group
    user:
      name: "{{ ansible_user }}"
      append: yes
      groups: docker
